scrape_configs:
  - job_name: 'movie_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['movie_service:8000']
  - job_name: 'auth_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['auth_service:8000']
  - job_name: 'payment_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['payment_service:8000']