scrape_configs:
  - job_name: 'movie_service'
    scrape_interval: 10s
    static_configs:
      - targets: ['movie_service:8000']
  - job_name: 'user_service'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'movie_service:8000' ]
  - job_name: 'payment_service'
    scrape_interval: 10s
    static_configs:
      - targets: [ 'movie_service:8000' ]